<?php

use AJUR\FSNews\Media;
use PHPUnit\Framework\TestCase;

/**
 * @testdox MediaTest class
 */
class MediaTest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        Media::init([
            'path.storage'     =>   '/srv/storage/',
            'path.watermarks'  =>   '/var/www/47news/www/frontend/images/watermarks/'
        ], []);
    }

    /**
     * @testdox get Absolute Resource Path
     * @return void
     */
    public function testGetAbsoluteResourcePath()
    {
        $this->assertEquals( '/srv/storage/videos/2023/05/', Media::getAbsoluteResourcePath('videos', '2023-05-05 17:11:44') );
    }

    /**
     * @return void
     * @testdox Get Relative Resource Path
     */
    public function testGetRelativeResourcePath()
    {
        $this->assertEquals('/videos/2023/05/', Media::getRelativeResourcePath('videos', '2023-05-05 17:17:44'));
    }

    /**
     * @return void
     * @testdox Deserialize correct
     */
    public function testDeserialize1()
    {
        $this->assertEquals(['a' => 1 ], Media\Helpers\MediaHelpers::deserialize('{"a": 1}', []));
    }

}